-- StudyVerse Admin + Study Group extension for MySQL/MariaDB
USE studyverse;

CREATE TABLE IF NOT EXISTS course_prerequisite (coursecode VARCHAR(10) NOT NULL, prereq_code VARCHAR(10) NOT NULL, prereq_type VARCHAR(10) NOT NULL, PRIMARY KEY(coursecode,prereq_code));
CREATE TABLE IF NOT EXISTS admin_work_due (
  workID INT AUTO_INCREMENT PRIMARY KEY, adminID VARCHAR(8) NOT NULL, title VARCHAR(150) NOT NULL,
  details VARCHAR(500) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'PENDING', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS admin_messages (
  messageID INT AUTO_INCREMENT PRIMARY KEY, fromAdmin VARCHAR(8) NOT NULL, toAdmin VARCHAR(8) NOT NULL,
  message VARCHAR(500) NOT NULL, status VARCHAR(20) DEFAULT 'UNREAD', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS content_reports (
  reportID INT AUTO_INCREMENT PRIMARY KEY, reporterID VARCHAR(8) NOT NULL, report_type VARCHAR(30) NOT NULL,
  targetID VARCHAR(20) NOT NULL, reason VARCHAR(500) NOT NULL, status VARCHAR(20) DEFAULT 'PENDING', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS admin_course_delete_requests (
  requestID INT AUTO_INCREMENT PRIMARY KEY, coursecode VARCHAR(10) NOT NULL, requestedBy VARCHAR(8) NOT NULL,
  status VARCHAR(20) DEFAULT 'PENDING', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS admin_course_delete_votes (
  requestID INT NOT NULL, adminID VARCHAR(8) NOT NULL, vote VARCHAR(3) NOT NULL,
  PRIMARY KEY(requestID, adminID)
);
CREATE TABLE IF NOT EXISTS repo_creation_requests (
  requestID INT AUTO_INCREMENT PRIMARY KEY, repoID VARCHAR(10) NOT NULL, coursecode VARCHAR(10) NOT NULL,
  requestedBy VARCHAR(8) NOT NULL, status VARCHAR(20) DEFAULT 'PENDING', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS group_join_requests (
  requestID INT AUTO_INCREMENT PRIMARY KEY, groupID VARCHAR(10) NOT NULL, student_UID VARCHAR(8) NOT NULL,
  status VARCHAR(20) DEFAULT 'PENDING', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS group_messages (
  messageID INT AUTO_INCREMENT PRIMARY KEY, groupID VARCHAR(10) NOT NULL, senderID VARCHAR(8) NOT NULL,
  message VARCHAR(500) NOT NULL, message_type VARCHAR(30) DEFAULT 'JOIN', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS group_weekly_goals (
  goalID INT AUTO_INCREMENT PRIMARY KEY, groupID VARCHAR(10) NOT NULL, studentID VARCHAR(8) NOT NULL,
  goal VARCHAR(300) NOT NULL, week_start DATE NOT NULL, completed TINYINT(1) DEFAULT 0,
  UNIQUE KEY uq_goal(groupID,studentID,week_start)
);

-- Needed for semester-aware course usage and grade-based performance.
ALTER TABLE course_student_took ADD COLUMN enrollment_semester VARCHAR(30) NULL;
ALTER TABLE course_student_took ADD COLUMN grade DECIMAL(5,2) NULL;

-- Optional useful performance counters for resources.
ALTER TABLE course_resouce ADD COLUMN view_count INT NOT NULL DEFAULT 0;
ALTER TABLE course_resouce ADD COLUMN download_count INT NOT NULL DEFAULT 0;
