<?php require 'admin_guard.php'; require 'admin_db.php';
$q=trim($_GET['q']??''); $filter=$_GET['filter']??'all'; $semester=trim($_GET['semester']??'');
$where=''; $params=[]; $types=''; if($q!==''){ $where=' WHERE c.coursecode LIKE ? OR c.name LIKE ?'; $params=["%$q%","%$q%"];$types='ss'; }
if($filter==='usage' && $semester!==''){ $where .= ($where?' AND ':' WHERE ').'e.enrollment_semester LIKE "'.mysqli_real_escape_string($conn,$semester).'"'; }
if($filter==='top') $order=' ORDER BY COALESCE(g.avggrade,0) DESC, COALESCE(fr.avgrating,0) DESC'; elseif($filter==='low') $order=' ORDER BY COALESCE(g.avggrade,0) ASC, COALESCE(fr.avgrating,0) ASC'; elseif($filter==='faculty') $order=' ORDER BY faculty_count DESC'; elseif($filter==='usage') $order=' ORDER BY student_count DESC'; else $order=' ORDER BY c.coursecode';
$sql="SELECT c.coursecode,c.name,COUNT(DISTINCT r.repoID) repo_count,COUNT(DISTINCT e.userID) student_count,COUNT(DISTINCT f.faculty_UID) faculty_count,ROUND(COALESCE(cr.avg_rate,0),2) course_rating,COALESCE(g.avggrade,0) avggrade,COALESCE(fr.avgrating,0) faculty_rating FROM course c LEFT JOIN repository r ON r.coursecode=c.coursecode LEFT JOIN course_student_took e ON e.coursecode=c.coursecode LEFT JOIN faculty_courselist f ON f.coursecode=c.coursecode LEFT JOIN (SELECT coursecode,AVG(rate) avg_rate FROM student_review_course GROUP BY coursecode) cr ON cr.coursecode=c.coursecode LEFT JOIN (SELECT coursecode,AVG(grade) avggrade FROM course_student_took WHERE grade IS NOT NULL GROUP BY coursecode) g ON g.coursecode=c.coursecode LEFT JOIN (SELECT fcl.coursecode,AVG(srf.rating) avgrating FROM faculty_courselist fcl JOIN student_rates_faculty srf ON srf.faculty_uID=fcl.faculty_UID GROUP BY fcl.coursecode) fr ON fr.coursecode=c.coursecode $where GROUP BY c.coursecode,c.name,cr.avg_rate,g.avggrade,fr.avgrating $order";
$stmt=mysqli_prepare($conn,$sql); if($q!=='') mysqli_stmt_bind_param($stmt,$types,...$params); mysqli_stmt_execute($stmt); $rows=mysqli_stmt_get_result($stmt);
?>
<!doctype html><html><head><title>All Course Info</title><link rel="stylesheet" href="admin_pages.css"></head><body><div class="page"><div class="top"><div><h1>All Course Information</h1><p class="muted">Search now; more search options can be added later.</p></div><a class="btn" href="admin_dashboard.php">Dashboard</a></div><div class="panel"><form class="filters"><input name="q" value="<?=htmlspecialchars($q)?>" placeholder="Search by course code or course name"><select name="filter"><option value="all">All courses</option><option value="top" <?=$filter==='top'?'selected':''?>>Top performing</option><option value="low" <?=$filter==='low'?'selected':''?>>Low performing</option><option value="usage" <?=$filter==='usage'?'selected':''?>>Top using / highest enrollment</option><option value="faculty" <?=$filter==='faculty'?'selected':''?>>Max faculty</option></select><input name="semester" value="<?=htmlspecialchars($semester)?>" placeholder="Semester for usage filter (e.g. Summer 2026)"><button>Apply</button></form></div><div class="panel tablewrap"><table><tr><th>Course Code</th><th>Course Name</th><th>Repo No.</th><th>Total Students</th><th>Total Faculty</th><th>Avg Rating</th><th>Performance Grade</th><th>Actions</th></tr><?php while($x=mysqli_fetch_assoc($rows)): ?><tr><td><?=htmlspecialchars($x['coursecode'])?></td><td><?=htmlspecialchars($x['name'])?></td><td><?=$x['repo_count']?></td><td><?=$x['student_count']?></td><td><?=$x['faculty_count']?></td><td><?=$x['course_rating']?></td><td><?=$x['avggrade']?></td><td class="actions"><a class="btn" href="edit_course.php?coursecode=<?=urlencode($x['coursecode'])?>">Update</a><a class="btn danger" href="delete_course.php?coursecode=<?=urlencode($x['coursecode'])?>">Delete</a></td></tr><?php endwhile;?></table></div><div class="panel"><h2>Course Actions</h2><a class="btn" href="insert_course.php">＋ Add Course</a></div></div></body></html>
